project_id = "hartico-tennis"

[api]
enabled = true
port = 54341
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54342
major_version = 17

[studio]
enabled = true
port = 54343

[auth]
enabled = true
site_url = "http://localhost:5175"
additional_redirect_urls = ["http://127.0.0.1:5175"]

[db.seed]
enabled = false
