project_id = "hartico-football"

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54332
major_version = 17

[studio]
enabled = true
port = 54333

[auth]
enabled = true
site_url = "http://localhost:5174"
additional_redirect_urls = ["http://127.0.0.1:5174"]

[db.seed]
enabled = false
